on:
  workflow_dispatch:
    inputs:
      updated-value:
        description: 'Updated value'
        required: true
        type: string

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: ryanditjia/demo-actions@registry
        with:
          updated-value: ${{ inputs.updated-value }}
          myToken: ${{ secrets.REGISTRY_UPDATE_TOKEN }}
