on:
  workflow_dispatch:
    inputs:
      web-player-env:
        description: 'Web player environment'
        required: true
        type: choice
        options:
          - prod
          - dev
      game-name:
        description: 'Game name'
        required: true
        type: string
      url-prefix:
        description: 'URL prefix to update'
        required: true
        type: string
      compression:
        description: 'Compression setting'
        type: choice
        options:
          - brotli
          - gzip
      

jobs:
  update-web-player-registry:
    runs-on: ubuntu-latest
    name: Update Web Player Registry
    steps:
      - name: Update Web Player Registry
        uses: ryanditjia/demo-actions@registry
        with:
          web-player-repo-pat: ${{ secrets.WEB_PLAYER_REPO_PAT }}
          web-player-env: ${{ inputs.web-player-env }}
          game-name: ${{ inputs.game-name }}
          url-prefix: ${{ inputs.url-prefix }}
          compression: ${{ inputs.compression }}
