name: Call Update Web Player Registry

on:
  workflow_dispatch:
    inputs:
      game_name:
        description: 'Game name'
        required: true
        type: string
      url_prefix:
        description: 'URL prefix to update'
        required: true
        type: string
      compression:
        description: 'Compression setting'
        type: choice
        options:
          - brotli
          - gzip

jobs:
  call-update:
    runs-on: ubuntu-latest
    steps:
      - name: Call Update Web Player Registry
        uses: ryanditjia/demo-actions/.github/actions/update-web-player-registry/action.yml@main
        with:
          game_name: ${{ inputs.game_name }}
          url_prefix: ${{ inputs.url_prefix }}
          compression: ${{ inputs.compression }}
